CREATE TABLE IF NOT EXISTS person (
    id SERIAL PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    last_name VARCHAR(255) NOT NULL
);
